Set up a very simple system with a single particle and shifted Lj wall forces. Then explicitly change the position of the particle along the x-axis (y=z=0) and compute the potential energy. Finally, plot this potential energy as a function of x.
'
what we need is basically a custom external force in every direction which is mostly 0. And only when you are within some distance to the "wall" at +- L/2 you switch on a Lennard Jones interaction
 All that we want is an external potential that is zero for -L/2 + cutoff < x < L/2 - cutoff and at this cutoff value the potential should start growing like LJ after the minimum

## OpenMM

In [122]:
import ase.io
import gsd.hoomd
import numpy.typing as npt
import openmm
from openmm import app
from openmm import unit
from openmm import CustomExternalForce


def read_xyz_file(filename: str) -> (list[str], npt.NDArray[float], npt.NDArray[float]):
    if not filename.endswith(".xyz"):
        raise ValueError("The file must have the .xyz extension.")
    atoms = ase.io.read(filename, format="extxyz")
    cell = atoms.get_cell()[:]
    assert cell.shape == (3, 3)
    return atoms.get_chemical_symbols(), atoms.get_positions(), cell

In [123]:
types, positions, cell = read_xyz_file('test_system.xyz')

In [124]:
topology = app.topology.Topology()
chain = topology.addChain()
residue = topology.addResidue("res1", chain)

for t in types:
    topology.addAtom(t, None, residue)

#topology.setPeriodicBoxVectors(cell)

system = openmm.System()

temperature=298
timestep=0.005
collision_rate=1

integrator = openmm.LangevinIntegrator(temperature,collision_rate, timestep)

masses=[1,1]
box_length=1000

for t in types:
    system.addParticle(masses[0])
    
platform_name= 'Reference'
    
platform = openmm.Platform.getPlatformByName(platform_name)
        
simulation = app.Simulation(topology, system, integrator, platform)

simulation.context.setPositions(positions)

slj_potential = CustomExternalForce(
    "step(-box_length/2 + r_cut + delta, box_length/2 - r_cut - delta) * "
    "4*epsilon*((radius/(x-delta))^12+(radius/(x-delta))^6) +(radius/(y-delta))^12+(radius/(y-delta))^6)(radius/(z-delta))^12+(radius/(z-delta))^6)"
    "r_cut = radius * 2 **(1/6)"
    "delta = radius - 1"
    )

slj_potential.addGlobalParameter("epsilon", 1.0)

slj_potential.addGlobalParameter("box_length",
                                    box_length) #.value_in_unit(self._nanometer))

slj_potential.addPerParticleParameter("x")
slj_potential.addPerParticleParameter("y")
slj_potential.addPerParticleParameter("z")
slj_potential.addPerParticleParameter("radius")

system.addForce(slj_potential)

        
simulation.reporters.append(app.StateDataReporter(None, 1, time=True,
                                                      kineticEnergy=False, potentialEnergy=True, temperature=False,
                                                      speed=False, append=None))



for i in range(0,101):
    
    positions[0][0]+=10
    print(positions)

    simulation.step(1)

[[ 9.35000002 -0.64999998 -0.64999998]]
#"Time (ps)","Potential Energy (kJ/mole)"
0.005,0.0
[[19.35000002 -0.64999998 -0.64999998]]
0.01,0.0
[[29.35000002 -0.64999998 -0.64999998]]
0.015,0.0
[[39.35000002 -0.64999998 -0.64999998]]
0.02,0.0
[[49.35000002 -0.64999998 -0.64999998]]
0.025,0.0
[[59.35000002 -0.64999998 -0.64999998]]
0.030000000000000002,0.0
[[69.35000002 -0.64999998 -0.64999998]]
0.035,0.0
[[79.35000002 -0.64999998 -0.64999998]]
0.04,0.0
[[89.35000002 -0.64999998 -0.64999998]]
0.045,0.0
[[99.35000002 -0.64999998 -0.64999998]]
0.049999999999999996,0.0
[[109.35000002  -0.64999998  -0.64999998]]
0.05499999999999999,0.0
[[119.35000002  -0.64999998  -0.64999998]]
0.05999999999999999,0.0
[[129.35000002  -0.64999998  -0.64999998]]
0.06499999999999999,0.0
[[139.35000002  -0.64999998  -0.64999998]]
0.06999999999999999,0.0
[[149.35000002  -0.64999998  -0.64999998]]
0.075,0.0
[[159.35000002  -0.64999998  -0.64999998]]
0.08,0.0
[[169.35000002  -0.64999998  -0.64999998]]
0.085,0.0
[[179

## HOOMD

In [125]:
import hoomd
import gsd.hoomd 

from hoomd import md

import numpy as np
import math
import itertools

In [126]:
N_particles = 1

box_length = 1000 #length of box

spacing = 1.3
K = math.ceil(N_particles ** (1 / 3))
L = K * spacing
x = np.linspace(-L / 2, L / 2, K, endpoint=False)
position = list(itertools.product(x, repeat=3))

radiusN=105
radiusP=85

frame = gsd.hoomd.Frame()
frame.particles.N = N_particles
frame.particles.position = position[0:N_particles]
frame.particles.typeid = [0]* N_particles
frame.configuration.box = [box_length, box_length, box_length, 0, 0, 0]

frame.particles.types = ['N']

In [127]:
with gsd.hoomd.open(name='test_system.gsd', mode='w') as f:
    f.append(frame)

In [129]:
hoomd.context.initialize("--mode=cpu")
system=hoomd.init.read_gsd('test_system.gsd',frame=-1)
snapshot = system.take_snapshot()

notice(2): Group "all" created containing 1 particles


In [130]:
upper_wall_x = hoomd.md.wall.plane(origin=(L/2,0,0),normal=(-1,0,0),inside=True)
lower_wall_x = hoomd.md.wall.plane(origin=(-L/2,0,0),normal=(1,0,0),inside=True)
upper_wall_y = hoomd.md.wall.plane(origin=(0,L/2,0),normal=(0,-1,0),inside=True)
lower_wall_y = hoomd.md.wall.plane(origin=(0,-L/2,0),normal=(0,1,0),inside=True)
upper_wall_z = hoomd.md.wall.plane(origin=(0,0,L/2),normal=(0,0,-1),inside=True)
lower_wall_z = hoomd.md.wall.plane(origin=(0,0,-L/2),normal=(0,0,1),inside=True)

wall_group = hoomd.md.wall.group(upper_wall_x,lower_wall_x,upper_wall_y,lower_wall_y,upper_wall_z,lower_wall_z)
wall_force = hoomd.md.wall.slj(wall_group,r_cut=radiusN*(2.0**(1.0/6.0)))
wall_force.force_coeff.set('N',epsilon=1,sigma=radiusN,alpha=0,r_cut=radiusN*(2.0**(1.0/6.0)))

notice(2): Notice: slj set d_max=1.0


In [131]:
hoomd.md.integrate.mode_standard(dt=0.005)
gamma=1
all = hoomd.group.all()

log = hoomd.analyze.log(filename=None,
                      quantities=['potential_energy', 'temperature'],
                      period=1,
                      overwrite=True,
                      phase=-1)


seed=1
integrator = hoomd.md.integrate.nvt(group=all,kT=1, tau=1/gamma)
integrator.randomize_velocities(seed=seed)

In [132]:
print(snapshot.box)

snapshot.box.periodic = np.array([True,True,True])

Box: Lx=1000.0 Ly=1000.0 Lz=1000.0 xy=0.0 xz=0.0 yz=0.0 dimensions=3


In [133]:
hoomd.md.integrate.mode_standard(dt=0.005)
gamma=1
all = hoomd.group.all()

log = hoomd.analyze.log(filename=None,
                      quantities=['potential_energy', 'temperature'],
                      period=1,
                      overwrite=True,
                      phase=-1)


seed=1
integrator = hoomd.md.integrate.nvt(group=all,kT=1, tau=1/gamma)
integrator.randomize_velocities(seed=seed)

*Warning*: compute.thermo already specified for a group with name __nvt_all


In [100]:


for i in range(0,101):
    
    
    hoomd.run(1)
    
    
    snapshot.particles.position[0][0] +=10
    print(snapshot.particles.position)
    
    print(log.query("potential_energy"))

*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:21 | Step 1 / 1 | TPS 4.09356 | ETA 00:00:00
Average TPS: 4.06365
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 9.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 2 / 2 | TPS 100000 | ETA 00:00:00
Average TPS: 3952.57
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[19.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 3 / 3 | TPS 200000 | ETA 00:00:00
Average TPS: 6410.26
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[29.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 4 / 4 | TPS 200000 | ETA 00:00:00
Average TPS: 6134.97
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[39.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 5 / 5 | TPS 250000 | ETA 00:00:00
Average TPS: 5405.41
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[49.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 6 / 6 | TPS 250000 | ETA 00:00:00
Average TPS: 5917.16
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[59.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 7 / 7 | TPS 100000 | ETA 00:00:00
Average TPS: 5050.51
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[69.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 8 / 8 | TPS 58823.5 | ETA 00:00:00
Average TPS: 3246.75
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[79.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 9 / 9 | TPS 58823.5 | ETA 00:00:00
Average TPS: 4048.58
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[89.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 10 / 10 | TPS 71428.6 | ETA 00:00:00
Average TPS: 4926.11
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[99.35 -0.65 -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 11 / 11 | TPS 90909.1 | ETA 00:00:00
Average TPS: 4926.11
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[109.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 12 / 12 | TPS 37037 | ETA 00:00:00
Average TPS: 1312.34
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[119.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 13 / 13 | TPS 83333.3 | ETA 00:00:00
Average TPS: 5649.72
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[129.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 14 / 14 | TPS 76923.1 | ETA 00:00:00
Average TPS: 4608.29
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[139.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 15 / 15 | TPS 90909.1 | ETA 00:00:00
Average TPS: 4184.1
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[149.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 16 / 16 | TPS 90909.1 | ETA 00:00:00
Average TPS: 5000
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[159.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 17 / 17 | TPS 71428.6 | ETA 00:00:00
Average TPS: 4291.85
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[169.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 18 / 18 | TPS 83333.3 | ETA 00:00:00
Average TPS: 3816.79
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[179.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 19 / 19 | TPS 52631.6 | ETA 00:00:00
Average TPS: 2415.46
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[189.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 20 / 20 | TPS 83333.3 | ETA 00:00:00
Average TPS: 3367
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[199.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 21 / 21 | TPS 125000 | ETA 00:00:00
Average TPS: 5000
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[209.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 22 / 22 | TPS 83333.3 | ETA 00:00:00
Average TPS: 5102.04
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[219.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 23 / 23 | TPS 100000 | ETA 00:00:00
Average TPS: 6250
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[229.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 24 / 24 | TPS 76923.1 | ETA 00:00:00
Average TPS: 4807.69
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[239.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 25 / 25 | TPS 90909.1 | ETA 00:00:00
Average TPS: 4566.21
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[249.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 26 / 26 | TPS 47619 | ETA 00:00:00
Average TPS: 3571.43
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[259.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 27 / 27 | TPS 142857 | ETA 00:00:00
Average TPS: 2967.36
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[269.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 28 / 28 | TPS 76923.1 | ETA 00:00:00
Average TPS: 4761.9
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[279.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 29 / 29 | TPS 111111 | ETA 00:00:00
Average TPS: 4739.34
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[289.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 30 / 30 | TPS 90909.1 | ETA 00:00:00
Average TPS: 2985.07
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[299.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 31 / 31 | TPS 111111 | ETA 00:00:00
Average TPS: 3623.19
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[309.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 32 / 32 | TPS 83333.3 | ETA 00:00:00
Average TPS: 4545.45
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[319.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 33 / 33 | TPS 100000 | ETA 00:00:00
Average TPS: 3558.72
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[329.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 34 / 34 | TPS 62500 | ETA 00:00:00
Average TPS: 3649.64
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[339.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 35 / 35 | TPS 50000 | ETA 00:00:00
Average TPS: 4366.81
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[349.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 36 / 36 | TPS 83333.3 | ETA 00:00:00
Average TPS: 5434.78
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[359.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 37 / 37 | TPS 166667 | ETA 00:00:00
Average TPS: 5235.6
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[369.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 38 / 38 | TPS 166667 | ETA 00:00:00
Average TPS: 4672.9
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[379.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 39 / 39 | TPS 83333.3 | ETA 00:00:00
Average TPS: 4219.41
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[389.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 40 / 40 | TPS 58823.5 | ETA 00:00:00
Average TPS: 3039.51
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[399.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:21 | Step 41 / 41 | TPS 100000 | ETA 00:00:00
Average TPS: 3225.81
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[409.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 42 / 42 | TPS 142857 | ETA 00:00:00
Average TPS: 5681.82
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[419.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 43 / 43 | TPS 142857 | ETA 00:00:00
Average TPS: 5154.64
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[429.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 44 / 44 | TPS 125000 | ETA 00:00:00
Average TPS: 5681.82
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[439.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 45 / 45 | TPS 166667 | ETA 00:00:00
Average TPS: 4672.9
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[449.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 46 / 46 | TPS 125000 | ETA 00:00:00
Average TPS: 6097.56
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[459.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 47 / 47 | TPS 100000 | ETA 00:00:00
Average TPS: 5376.34
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[469.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 48 / 48 | TPS 62500 | ETA 00:00:00
Average TPS: 1934.24
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[479.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 49 / 49 | TPS 83333.3 | ETA 00:00:00
Average TPS: 5076.14
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[489.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 50 / 50 | TPS 166667 | ETA 00:00:00
Average TPS: 5000
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[499.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 51 / 51 | TPS 142857 | ETA 00:00:00
Average TPS: 5617.98
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[509.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 52 / 52 | TPS 142857 | ETA 00:00:00
Average TPS: 5434.78
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[519.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 53 / 53 | TPS 125000 | ETA 00:00:00
Average TPS: 5319.15
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[529.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 54 / 54 | TPS 166667 | ETA 00:00:00
Average TPS: 5917.16
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[539.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 55 / 55 | TPS 142857 | ETA 00:00:00
Average TPS: 3663
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[549.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 56 / 56 | TPS 83333.3 | ETA 00:00:00
Average TPS: 3039.51
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[559.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 57 / 57 | TPS 83333.3 | ETA 00:00:00
Average TPS: 5291.01
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[569.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 58 / 58 | TPS 142857 | ETA 00:00:00
Average TPS: 5681.82
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[579.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 59 / 59 | TPS 166667 | ETA 00:00:00
Average TPS: 4149.38
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[589.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 60 / 60 | TPS 142857 | ETA 00:00:00
Average TPS: 5464.48
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[599.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 61 / 61 | TPS 125000 | ETA 00:00:00
Average TPS: 3496.5
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[609.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 62 / 62 | TPS 166667 | ETA 00:00:00
Average TPS: 2890.17
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[619.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 63 / 63 | TPS 166667 | ETA 00:00:00
Average TPS: 5291.01
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[629.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 64 / 64 | TPS 62500 | ETA 00:00:00
Average TPS: 5128.21
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[639.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 65 / 65 | TPS 90909.1 | ETA 00:00:00
Average TPS: 5208.33
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[649.35  -0.65  -0.65]]
0.0
** starting run **
Time 00:00:22 | Step 66 / 66 | TPS 142857 | ETA 00:00:00
Average TPS: 5235.6
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 6.5935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 67 / 67 | TPS 200000 | ETA 00:00:00
Average TPS: 5714.29
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 6.6935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 68 / 68 | TPS 166667 | ETA 00:00:00
Average TPS: 3891.05
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 6.7935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 69 / 69 | TPS 83333.3 | ETA 00:00:00
Average TPS: 4854.37
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 6.8935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 70 / 70 | TPS 62500 | ETA 00:00:00
Average TPS: 4166.67
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 6.9935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 71 / 71 | TPS 125000 | ETA 00:00:00
Average TPS: 5494.51
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 7.0935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 72 / 72 | TPS 142857 | ETA 00:00:00
Average TPS: 5847.95
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 7.1935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 73 / 73 | TPS 166667 | ETA 00:00:00
Average TPS: 6211.18
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 7.2935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 74 / 74 | TPS 200000 | ETA 00:00:00
Average TPS: 5847.95
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 7.3935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 75 / 75 | TPS 166667 | ETA 00:00:00
Average TPS: 4784.69
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 7.4935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 76 / 76 | TPS 250000 | ETA 00:00:00
Average TPS: 5617.98
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 7.5935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 77 / 77 | TPS 100000 | ETA 00:00:00
Average TPS: 3861
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 7.6935e+02 -6.5000e-01 -6.5000e-01]]
0.0


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 78 / 78 | TPS 34482.8 | ETA 00:00:00
Average TPS: 2785.52
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 7.7935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 79 / 79 | TPS 62500 | ETA 00:00:00
Average TPS: 5291.01
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 7.8935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 80 / 80 | TPS 142857 | ETA 00:00:00
Average TPS: 2958.58
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 7.9935e+02 -6.5000e-01 -6.5000e-01]]
0.0


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 81 / 81 | TPS 142857 | ETA 00:00:00
Average TPS: 3731.34
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 8.0935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 82 / 82 | TPS 142857 | ETA 00:00:00
Average TPS: 5050.51
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 8.1935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 83 / 83 | TPS 142857 | ETA 00:00:00
Average TPS: 5405.41
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 8.2935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 84 / 84 | TPS 142857 | ETA 00:00:00
Average TPS: 5952.38
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 8.3935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 85 / 85 | TPS 76923.1 | ETA 00:00:00
Average TPS: 4545.45
---------
** run complete **
[[ 8.4935e+02 -6.5000e-01 -6.5000e-01]]

*Warning*: compute.thermo: given a group with 0 degrees of freedom.



0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 86 / 86 | TPS 76923.1 | ETA 00:00:00
Average TPS: 3095.98
---------
** run complete **
[[ 8.5935e+02 -6.5000e-01 -6.5000e-01]]
0.0


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 87 / 87 | TPS 125000 | ETA 00:00:00
Average TPS: 4115.23
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 8.6935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 88 / 88 | TPS 142857 | ETA 00:00:00
Average TPS: 5347.59
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 8.7935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 89 / 89 | TPS 111111 | ETA 00:00:00
Average TPS: 5319.15
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 8.8935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 90 / 90 | TPS 111111 | ETA 00:00:00
Average TPS: 4651.16
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 8.9935e+02 -6.5000e-01 -6.5000e-01]]
0.0


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 91 / 91 | TPS 111111 | ETA 00:00:00
Average TPS: 4901.96
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 9.0935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 92 / 92 | TPS 90909.1 | ETA 00:00:00
Average TPS: 5405.41
---------
** run complete **
[[ 9.1935e+02 -6.5000e-01 -6.5000e-01]]
0.0


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 93 / 93 | TPS 41666.7 | ETA 00:00:00
Average TPS: 3105.59
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 9.2935e+02 -6.5000e-01 -6.5000e-01]]
0.0


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 94 / 94 | TPS 90909.1 | ETA 00:00:00
Average TPS: 4524.89
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 9.3935e+02 -6.5000e-01 -6.5000e-01]]
0.0


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 95 / 95 | TPS 166667 | ETA 00:00:00
Average TPS: 2932.55
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 9.4935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 96 / 96 | TPS 142857 | ETA 00:00:00
Average TPS: 4975.12
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 9.5935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 97 / 97 | TPS 166667 | ETA 00:00:00
Average TPS: 3225.81
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


[[ 9.6935e+02 -6.5000e-01 -6.5000e-01]]
0.0
** starting run **
Time 00:00:22 | Step 98 / 98 | TPS 200000 | ETA 00:00:00
Average TPS: 5076.14
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 9.7935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 99 / 99 | TPS 200000 | ETA 00:00:00
Average TPS: 5434.78
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 9.8935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 100 / 100 | TPS 58823.5 | ETA 00:00:00
Average TPS: 5025.13
---------
** run complete **


*Warning*: compute.thermo: given a group with 0 degrees of freedom.


[[ 9.9935e+02 -6.5000e-01 -6.5000e-01]]
0.0


            overriding ndof=1 to avoid divide by 0 errors
*Warning*: compute.thermo: given a group with 0 degrees of freedom.
            overriding ndof=1 to avoid divide by 0 errors


** starting run **
Time 00:00:22 | Step 101 / 101 | TPS 71428.6 | ETA 00:00:00
Average TPS: 4926.11
---------
** run complete **
[[ 1.00935e+03 -6.50000e-01 -6.50000e-01]]
0.0


In [101]:
frame = gsd.hoomd.Frame()
frame.particles.N = N_particles
frame.particles.position = snapshot.particles.position
frame.particles.typeid = [0]* N_particles
frame.configuration.box = [box_length, box_length, box_length, 0, 0, 0]

with gsd.hoomd.open(name='move.gsd', mode='w') as f:
    f.append(frame)

In [102]:
r_cut=radiusN*(2.0**(1.0/6.0))

r_cut

117.85851507248417

In [88]:
snapshot.particles.position

array([[ 9.8935e+02, -6.5000e-01, -6.5000e-01]], dtype=float32)